---
# Content type labels (auto-applied by labeler.yml)
- name: "software"
  color: 1d76db
  description: "Changes to software catalog entries"
- name: "hardware"
  color: 5319e7
  description: "Changes to hardware catalog entries"
- name: "manufacturer"
  color: 006b75
  description: "Changes to manufacturer entries"
- name: "schema"
  color: fbca04
  description: "Changes to catalog schemas"

# PR status labels (managed by pr-review.yml)
- name: "ready-for-review"
  color: 0e8a16
  description: "PR has passed all checks and is ready for review"
- name: "broken-urls"
  color: d93f0b
  description: "PR contains broken or unreachable URLs"

# Contribution labels
- name: "new-entry"
  color: 0e8a16
  description: "Adds a new catalog entry"
- name: "update"
  color: 1d76db
  description: "Updates an existing catalog entry"
- name: "bot"
  color: bfdadc
  description: "Created by Racks Catalog Bot"

# Issue/PR type labels
- name: "bug"
  color: b60205
  description: "Incorrect or missing data in the catalog"
- name: "enhancement"
  color: 006b75
  description: "Improvement to existing entries"
- name: "duplicate"
  color: cfd3d7
  description: "Duplicate entry detected"

# Workflow labels
- name: "ci"
  color: 5319e7
  description: "Changes to CI/CD workflows"
- name: "scripts"
  color: 0052cc
  description: "Changes to build/validation scripts"
- name: "documentation"
  color: 0052cc
  description: "Documentation updates"
