title: "[Add Manufacturer] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Request to add a new manufacturer to the catalog.

        > **Tip:** Maintainers can use `/help` to see available slash commands for processing this request.

  - type: input
    id: name
    attributes:
      label: Manufacturer Name
      description: The full company or developer name
      placeholder: e.g., Xfer Records
    validations:
      required: true

  - type: input
    id: website
    attributes:
      label: Website
      description: Link to the manufacturer's website
      placeholder: https://...
    validations:
      required: true

  - type: textarea
    id: products
    attributes:
      label: Notable Products
      description: List some of their popular plugins or software
      placeholder: |
        - Serum
        - LFO Tool
        - Nerve

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any other relevant information about this manufacturer
