title: "[Add] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Request to add a manufacturer to the catalog.

        **Note:** Manufacturer submissions require manual processing because they can involve crawling many product pages.

  - type: input
    id: url
    attributes:
      label: URL
      description: Link to the manufacturer's main website or products page
      placeholder: https://www.fabfilter.com/

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes (optional)
      description: Anything else we should know? (e.g., specific products to include)
