/**
 * Bulk data fix script for import cleanup
 *
 * Usage:
 *   tsx scripts/fix-data.ts categories       # Fix invalid categories + dedup
 *   tsx scripts/fix-data.ts block-scalars     # Convert details/specs arrays to |- block scalars
 *   tsx scripts/fix-data.ts videos            # Remove redundant provider: youtube
 *   tsx scripts/fix-data.ts io-categories     # Fix hardware IO categories (audio → digital)
 *   tsx scripts/fix-data.ts extract-formats   # Move format/host categories to formats/compatibleWith
 *   tsx scripts/fix-data.ts content-cleanup   # Remove platforms + software-centric categories from content
 *   tsx scripts/fix-data.ts truncated-descriptions  # Replace truncated descriptions from details field
 *   tsx scripts/fix-data.ts all               # Run all in sequence (excludes content-cleanup)
 *   tsx scripts/fix-data.ts --dry-run <cmd>   # Preview changes without writing
 */

import fs from "node:fs";
import path from "node:path";
import { isMap, isPair, isScalar, isSeq, parseDocument, Scalar, YAMLSeq } from "yaml";
import { loadSchemaContext } from "./lib/schema-loader.js";

const REPO_ROOT = path.resolve(import.meta.dirname, "..");
const DATA_DIR = path.join(REPO_ROOT, "data");

// =============================================================================
// CATEGORY MAPPING TABLE
// =============================================================================

// Maps invalid categories generated by the import pipeline to valid schema categories
const CATEGORY_MAP: Record<string, string> = {
  // Content & Assets
  soundbank: "preset-pack",
  "sound-bank": "preset-pack",
  soundset: "preset-pack",
  "sound-set": "preset-pack",
  "preset-library": "preset-pack",
  "patch-library": "preset-pack",
  "expansion-pack": "preset-pack",
  expansion: "preset-pack",
  presets: "preset",
  "sound-effect": "sample-pack",
  "sound-effects": "sample-pack",
  "sound-pack": "sample-pack",
  sample: "sample-pack",
  samples: "sample-pack",
  "sample-library": "sound-library",
  "music-library": "sound-library",
  "sample-kit": "sample-pack",
  loop: "loop-pack",
  loops: "loop-pack",
  "drum-loops": "loop-pack",
  "drum-loop": "loop-pack",
  refill: "preset-pack",
  "kontakt-instrument": "virtual-instrument",
  instrument: "virtual-instrument",

  // Drums
  drum: "drums",
  "drum-samples": "sample-pack",
  "drum-sample": "sample-pack",
  "drum-replacement": "sample-pack",
  "drum-stems": "sample-pack",
  "drum-multi-tracks": "sample-pack",
  "drum-track": "sample-pack",
  "kick-drum": "kick",

  // Effects / Processing
  "audio-effect": "effect",
  "audio-plugin": "plugin",
  saturator: "saturation",
  "dynamic-eq": "dynamics",
  clipper: "de-clipper",
  bitcrusher: "bit-crusher",
  maximizer: "limiter",
  "vocal-processor": "effect",
  "graphic-equalizer": "equalizer",
  "stereo-imaging": "stereo-widener",
  imaging: "stereo-widener",
  processor: "effect",
  "monitor-controller": "utility",

  // Synthesis
  "modular-synthesizer": "modular",
  "fm-synthesis": "fm",
  "bass-synth": "synthesizer",
  "acid-bass": "synthesizer",

  // Spatial
  "immersive-audio": "immersive",
  ambisonics: "spatial",

  // Misc
  "guitar-amp": "guitar-amplifier",
  "midi-interface": "midi-controller",
  "midi-pack": "midi",
  "chord-pack": "chord-generator",
  "audio-to-midi-converter": "utility",
  "audio-analysis": "analyzer",
  "audio-unit": "plugin",
  "sound-design": "creative",
  "field-recording": "sample-pack",
  "time-stretch": "utility",
  rack: "utility",
  mixing: "utility",
  host: "daw",
  adapter: "utility",
  "one-shot": "sample-pack",
  string: "strings",
  library: "sound-library",
  beat: "sample-pack",
  chiptune: "lo-fi",
  "8-bit": "lo-fi",
  808: "drum-machine",
};

// Categories to simply remove (not mappable to anything meaningful)
const CATEGORIES_TO_REMOVE = new Set([
  "omnisphere", // host app name, not a category
  "hip-hop", // genre not in schema
  "trap", // genre not in schema
  "pad", // too generic
  "ableton", // host app name
]);

// =============================================================================
// HELPERS
// =============================================================================

function getYamlFiles(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".yaml") || f.endsWith(".yml"))
    .map((f) => path.join(dir, f));
}

function getAllDataFiles(collections?: string[]): string[] {
  const dirs = collections ?? ["manufacturers", "software", "content", "hardware", "accessories"];
  return dirs.flatMap((c) => getYamlFiles(path.join(DATA_DIR, c)));
}

function relPath(file: string): string {
  return path.relative(REPO_ROOT, file);
}

// =============================================================================
// COMMAND: categories
// =============================================================================

function fixCategories(dryRun: boolean): number {
  const schema = loadSchemaContext();
  const validCategories = new Set(schema.categories);
  const aliasMap = schema.categoryAliases;
  let totalChanges = 0;

  const files = getAllDataFiles(["software", "content", "hardware", "accessories"]);

  for (const file of files) {
    const content = fs.readFileSync(file, "utf-8");
    const doc = parseDocument(content);
    const data = doc.toJSON() as Record<string, unknown>;
    let changed = false;

    // Fix primaryCategory
    if (typeof data.primaryCategory === "string") {
      const pc = data.primaryCategory;
      if (!validCategories.has(pc) && !aliasMap[pc]) {
        if (CATEGORY_MAP[pc]) {
          console.log(`  ${relPath(file)}: primaryCategory '${pc}' → '${CATEGORY_MAP[pc]}'`);
          doc.set("primaryCategory", CATEGORY_MAP[pc]);
          changed = true;
        } else if (CATEGORIES_TO_REMOVE.has(pc)) {
          console.log(`  ${relPath(file)}: primaryCategory '${pc}' → removing (unmappable)`);
          // Can't remove primaryCategory (required) — set to 'other'
          doc.set("primaryCategory", "other");
          changed = true;
        } else {
          console.log(`  ⚠ ${relPath(file)}: primaryCategory '${pc}' — NO MAPPING FOUND`);
        }
      }
    }

    // Fix categories array
    const categoriesNode = doc.get("categories");
    if (isSeq(categoriesNode)) {
      const updatedPrimary = (doc.toJSON() as Record<string, unknown>).primaryCategory as string;
      const secondaryCategory = data.secondaryCategory as string | undefined;
      const seen = new Set<string>();
      const toRemoveIndices: number[] = [];

      for (let i = 0; i < categoriesNode.items.length; i++) {
        const item = categoriesNode.items[i];
        const val =
          typeof item === "object" && item !== null && "value" in item
            ? (item as Scalar).value
            : item;
        if (typeof val !== "string") continue;

        let finalVal = val;

        // Remap invalid categories
        if (!validCategories.has(val) && !aliasMap[val]) {
          if (CATEGORY_MAP[val]) {
            finalVal = CATEGORY_MAP[val];
            console.log(`  ${relPath(file)}: categories[${i}] '${val}' → '${finalVal}'`);
            categoriesNode.set(i, finalVal);
            changed = true;
          } else if (CATEGORIES_TO_REMOVE.has(val)) {
            toRemoveIndices.push(i);
            console.log(`  ${relPath(file)}: categories[${i}] '${val}' → removed`);
            changed = true;
            continue;
          } else {
            console.log(`  ⚠ ${relPath(file)}: categories[${i}] '${val}' — NO MAPPING FOUND`);
            continue;
          }
        }

        // Track for dedup
        if (finalVal === updatedPrimary || finalVal === secondaryCategory || seen.has(finalVal)) {
          toRemoveIndices.push(i);
          if (finalVal === updatedPrimary) {
            console.log(
              `  ${relPath(file)}: categories[${i}] '${finalVal}' → removed (duplicate of primaryCategory)`
            );
          } else if (finalVal === secondaryCategory) {
            console.log(
              `  ${relPath(file)}: categories[${i}] '${finalVal}' → removed (duplicate of secondaryCategory)`
            );
          } else {
            console.log(`  ${relPath(file)}: categories[${i}] '${finalVal}' → removed (duplicate)`);
          }
          changed = true;
          continue;
        }
        seen.add(finalVal);
      }

      // Remove items in reverse order to preserve indices
      for (const idx of toRemoveIndices.sort((a, b) => b - a)) {
        categoriesNode.items.splice(idx, 1);
      }

      // Remove empty categories array
      if (categoriesNode.items.length === 0) {
        doc.delete("categories");
        console.log(`  ${relPath(file)}: removed empty categories array`);
        changed = true;
      }
    }

    if (changed) {
      totalChanges++;
      if (!dryRun) {
        fs.writeFileSync(file, doc.toString());
      }
    }
  }

  return totalChanges;
}

// =============================================================================
// COMMAND: block-scalars
// =============================================================================

function fixBlockScalars(dryRun: boolean): number {
  let totalChanges = 0;
  const files = getAllDataFiles(["software", "content", "hardware", "accessories"]);

  for (const file of files) {
    const content = fs.readFileSync(file, "utf-8");
    const doc = parseDocument(content);
    let changed = false;

    // Fix details: array → block scalar
    const detailsNode = doc.get("details");
    if (isSeq(detailsNode)) {
      const items = detailsNode.items.map((item) => {
        if (typeof item === "object" && item !== null && "value" in item)
          return String((item as Scalar).value);
        return String(item);
      });
      const blockText = items.join("\n\n");
      const scalar = new Scalar(blockText);
      scalar.type = Scalar.BLOCK_LITERAL;
      doc.set("details", scalar);
      console.log(`  ${relPath(file)}: details array (${items.length} items) → block scalar`);
      changed = true;
    }

    // Fix specs: array → block scalar with "- " prefix
    const specsNode = doc.get("specs");
    if (isSeq(specsNode)) {
      const items = specsNode.items.map((item) => {
        if (typeof item === "object" && item !== null && "value" in item)
          return String((item as Scalar).value);
        return String(item);
      });
      const blockText = items.map((item) => `- ${item}`).join("\n");
      const scalar = new Scalar(blockText);
      scalar.type = Scalar.BLOCK_LITERAL;
      doc.set("specs", scalar);
      console.log(`  ${relPath(file)}: specs array (${items.length} items) → block scalar`);
      changed = true;
    }

    if (changed) {
      totalChanges++;
      if (!dryRun) {
        fs.writeFileSync(file, doc.toString());
      }
    }
  }

  return totalChanges;
}

// =============================================================================
// COMMAND: videos
// =============================================================================

function fixVideos(dryRun: boolean): number {
  let totalChanges = 0;
  const files = getAllDataFiles(["software", "content", "hardware", "accessories"]);

  for (const file of files) {
    const content = fs.readFileSync(file, "utf-8");
    const doc = parseDocument(content);
    let changed = false;

    const videosNode = doc.get("videos");
    if (isSeq(videosNode)) {
      for (let i = 0; i < videosNode.items.length; i++) {
        const videoMap = videosNode.items[i];
        if (isMap(videoMap)) {
          const providerPair = videoMap.items.find(
            (p) => isPair(p) && (p.key as Scalar)?.value === "provider"
          );
          if (providerPair && isPair(providerPair)) {
            const providerVal = (providerPair.value as Scalar)?.value;
            if (providerVal === "youtube") {
              videoMap.items = videoMap.items.filter(
                (p) => !(isPair(p) && (p.key as Scalar)?.value === "provider")
              );
              console.log(`  ${relPath(file)}: videos[${i}] removed redundant provider: youtube`);
              changed = true;
            }
          }
        }
      }
    }

    if (changed) {
      totalChanges++;
      if (!dryRun) {
        fs.writeFileSync(file, doc.toString());
      }
    }
  }

  return totalChanges;
}

// =============================================================================
// COMMAND: io-categories
// =============================================================================

function fixIOCategories(dryRun: boolean): number {
  let totalChanges = 0;
  const digitalTypes = new Set(["s/pdif", "adat", "aes/ebu", "word clock", "dante"]);
  const files = getAllDataFiles(["hardware"]);

  for (const file of files) {
    const content = fs.readFileSync(file, "utf-8");
    const doc = parseDocument(content);
    let changed = false;

    const ioNode = doc.get("io");
    if (isSeq(ioNode)) {
      for (let i = 0; i < ioNode.items.length; i++) {
        const ioMap = ioNode.items[i];
        if (isMap(ioMap)) {
          const data = ioMap.toJSON() as Record<string, unknown>;
          const ioType = data.type as string | undefined;
          const ioCat = data.category as string | undefined;

          if (ioType && digitalTypes.has(ioType) && ioCat === "audio") {
            // Find the category pair and update it
            for (const pair of ioMap.items) {
              if (isPair(pair) && (pair.key as Scalar)?.value === "category") {
                (pair.value as Scalar).value = "digital";
                const name = data.name || `io[${i}]`;
                console.log(
                  `  ${relPath(file)}: ${name} category 'audio' → 'digital' (type: ${ioType})`
                );
                changed = true;
                break;
              }
            }
          }
        }
      }
    }

    if (changed) {
      totalChanges++;
      if (!dryRun) {
        fs.writeFileSync(file, doc.toString());
      }
    }
  }

  return totalChanges;
}

// =============================================================================
// COMMAND: extract-formats
// =============================================================================

// Category values that are actually plugin formats
const FORMAT_CATEGORY_MAP: Record<string, string> = {
  "audio-unit": "au",
  vst3: "vst3",
  aax: "aax",
  lv2: "lv2",
  "rack-extension": "rack-extension",
  "pro-tools": "aax",
  "pro-tools-plugin": "aax",
};

// Category values that are actually host/DAW references
const HOST_CATEGORY_MAP: Record<string, string> = {
  "ableton-live": "ableton-live",
  ableton: "ableton-live",
  kontakt: "kontakt",
};

function extractFormats(dryRun: boolean): number {
  let totalChanges = 0;
  const files = getAllDataFiles(["software"]);

  for (const file of files) {
    const content = fs.readFileSync(file, "utf-8");
    const doc = parseDocument(content);
    const data = doc.toJSON() as Record<string, unknown>;
    let changed = false;

    const formatsToAdd = new Set<string>();
    const hostsToAdd = new Set<string>();
    const indicesToRemove: number[] = [];

    // Check primaryCategory for format/host misuse
    const pc = data.primaryCategory as string | undefined;
    if (pc && FORMAT_CATEGORY_MAP[pc]) {
      formatsToAdd.add(FORMAT_CATEGORY_MAP[pc]);
      // Replace primaryCategory with 'plugin' since we can't leave it empty
      doc.set("primaryCategory", "plugin");
      console.log(
        `  ${relPath(file)}: primaryCategory '${pc}' → 'plugin' (extracted format '${FORMAT_CATEGORY_MAP[pc]}')`
      );
      changed = true;
    } else if (pc && HOST_CATEGORY_MAP[pc]) {
      hostsToAdd.add(HOST_CATEGORY_MAP[pc]);
      doc.set("primaryCategory", "plugin");
      console.log(
        `  ${relPath(file)}: primaryCategory '${pc}' → 'plugin' (extracted host '${HOST_CATEGORY_MAP[pc]}')`
      );
      changed = true;
    }

    // Scan categories array for format/host values
    const categoriesNode = doc.get("categories");
    if (isSeq(categoriesNode)) {
      for (let i = 0; i < categoriesNode.items.length; i++) {
        const item = categoriesNode.items[i];
        const val =
          typeof item === "object" && item !== null && "value" in item
            ? (item as Scalar).value
            : item;
        if (typeof val !== "string") continue;

        if (FORMAT_CATEGORY_MAP[val]) {
          formatsToAdd.add(FORMAT_CATEGORY_MAP[val]);
          indicesToRemove.push(i);
          console.log(
            `  ${relPath(file)}: categories[${i}] '${val}' → formats '${FORMAT_CATEGORY_MAP[val]}'`
          );
          changed = true;
        } else if (HOST_CATEGORY_MAP[val]) {
          hostsToAdd.add(HOST_CATEGORY_MAP[val]);
          indicesToRemove.push(i);
          console.log(
            `  ${relPath(file)}: categories[${i}] '${val}' → compatibleWith '${HOST_CATEGORY_MAP[val]}'`
          );
          changed = true;
        }
      }

      // Remove extracted items in reverse order
      for (const idx of indicesToRemove.sort((a, b) => b - a)) {
        categoriesNode.items.splice(idx, 1);
      }

      // Remove empty categories array
      if (categoriesNode.items.length === 0) {
        doc.delete("categories");
      }
    }

    // Merge extracted formats into existing formats array
    if (formatsToAdd.size > 0) {
      const existing = (doc.toJSON() as Record<string, unknown>).formats as string[] | undefined;
      const merged = new Set(existing ?? []);
      for (const f of formatsToAdd) merged.add(f);
      const formatsArr = new YAMLSeq();
      for (const f of merged) formatsArr.add(f);
      doc.set("formats", formatsArr);
    }

    // Merge extracted hosts into existing compatibleWith array
    if (hostsToAdd.size > 0) {
      const existing = (doc.toJSON() as Record<string, unknown>).compatibleWith as
        | string[]
        | undefined;
      const merged = new Set(existing ?? []);
      for (const h of hostsToAdd) merged.add(h);
      const hostsArr = new YAMLSeq();
      for (const h of merged) hostsArr.add(h);
      doc.set("compatibleWith", hostsArr);
    }

    if (changed) {
      totalChanges++;
      if (!dryRun) {
        fs.writeFileSync(file, doc.toString());
      }
    }
  }

  return totalChanges;
}

// =============================================================================
// COMMAND: content-cleanup
// =============================================================================

// Categories that describe the host software type, not the content itself.
// These should be removed from content entries — the `compatibleWith` field
// is the proper way to reference host software.
const SOFTWARE_CENTRIC_CATEGORIES = new Set([
  "synthesizer",
  "plugin",
  "effect",
  "sampler",
  "drum-machine",
  "virtual-instrument",
  "sequencer",
]);

function fixContentCleanup(dryRun: boolean): number {
  const files = getAllDataFiles(["content"]);
  let totalChanges = 0;

  for (const file of files) {
    const content = fs.readFileSync(file, "utf-8");
    const doc = parseDocument(content);
    let changed = false;

    // Strip platforms field (software-only, not valid for content)
    if (doc.has("platforms")) {
      doc.delete("platforms");
      console.log(`  ${relPath(file)}: removed platforms`);
      changed = true;
    }

    // Strip software-centric categories
    const categoriesNode = doc.get("categories");
    if (isSeq(categoriesNode)) {
      const indicesToRemove: number[] = [];

      for (let i = 0; i < categoriesNode.items.length; i++) {
        const item = categoriesNode.items[i];
        const val =
          typeof item === "object" && item !== null && "value" in item
            ? (item as Scalar).value
            : item;
        if (typeof val === "string" && SOFTWARE_CENTRIC_CATEGORIES.has(val)) {
          indicesToRemove.push(i);
          console.log(`  ${relPath(file)}: removed category '${val}'`);
          changed = true;
        }
      }

      // Remove in reverse order to preserve indices
      for (const idx of indicesToRemove.sort((a, b) => b - a)) {
        categoriesNode.items.splice(idx, 1);
      }

      // Remove empty categories array
      if (categoriesNode.items.length === 0) {
        doc.delete("categories");
        console.log(`  ${relPath(file)}: removed empty categories array`);
        changed = true;
      }
    }

    if (changed) {
      totalChanges++;
      if (!dryRun) {
        fs.writeFileSync(file, doc.toString());
      }
    }
  }

  return totalChanges;
}

// =============================================================================
// COMMAND: truncated-descriptions
// =============================================================================

function fixTruncatedDescriptions(dryRun: boolean): number {
  let totalChanges = 0;
  const files = getAllDataFiles(["software", "content", "hardware", "accessories"]);

  for (const file of files) {
    const content = fs.readFileSync(file, "utf-8");
    const doc = parseDocument(content);
    const data = doc.toJSON() as Record<string, unknown>;

    const description = data.description;
    if (typeof description !== "string") continue;
    if (!/\.{3,}\s*$/.test(description)) continue;

    // Description is truncated — try to replace from details
    const details = data.details;
    if (typeof details !== "string" || details.trim().length === 0) {
      console.log(`  ⚠ ${relPath(file)}: truncated description but no details field — skipping`);
      continue;
    }

    // Extract first paragraph from details and normalize whitespace
    // Details block scalars have line-wrapped text; collapse to single line
    const paragraphs = details.split(/\n\n+/);
    let replacement = paragraphs[0].replace(/\n/g, " ").replace(/\s+/g, " ").trim();

    // If the first paragraph is very long, use the first 2 sentences instead
    if (replacement.length > 500) {
      const sentences = replacement.match(/[^.!?]+[.!?]+/g);
      if (sentences && sentences.length >= 2) {
        replacement = sentences.slice(0, 2).join("").trim();
      }
    }

    // Update the description node in the YAML AST
    const descNode = doc.get("description", true);
    if (isScalar(descNode)) {
      descNode.value = replacement;
      console.log(`  ${relPath(file)}: description replaced from details`);
    } else {
      doc.set("description", replacement);
      console.log(`  ${relPath(file)}: description set from details`);
    }

    totalChanges++;
    if (!dryRun) {
      fs.writeFileSync(file, doc.toString());
    }
  }

  return totalChanges;
}

// =============================================================================
// MAIN
// =============================================================================

const args = process.argv.slice(2);
const dryRun = args.includes("--dry-run");
const command = args.find((a) => a !== "--dry-run") ?? "all";

if (dryRun) {
  console.log("🔍 DRY RUN — no files will be modified\n");
}

const commands: Record<string, (dryRun: boolean) => number> = {
  categories: fixCategories,
  "block-scalars": fixBlockScalars,
  videos: fixVideos,
  "io-categories": fixIOCategories,
  "extract-formats": extractFormats,
  "content-cleanup": fixContentCleanup,
  "truncated-descriptions": fixTruncatedDescriptions,
};

function runCommand(name: string, fn: (dryRun: boolean) => number): void {
  console.log(`\n━━━ ${name} ━━━`);
  const count = fn(dryRun);
  console.log(`\n✅ ${name}: ${count} files ${dryRun ? "would be" : ""} modified`);
}

// Commands excluded from "all" (one-time cleanups, not recurring fixes)
const excludeFromAll = new Set(["content-cleanup", "truncated-descriptions"]);

if (command === "all") {
  for (const [name, fn] of Object.entries(commands)) {
    if (excludeFromAll.has(name)) continue;
    runCommand(name, fn);
  }
} else if (commands[command]) {
  runCommand(command, commands[command]);
} else {
  console.error(`Unknown command: ${command}`);
  console.error(`Available: ${Object.keys(commands).join(", ")}, all`);
  process.exit(1);
}
