#!/usr/bin/env tsx
/**
 * Generate schema context file for Claude /add-entry command
 *
 * This script reads all schema YAML files and generates a single
 * markdown file (schema/CONTEXT.md) that Claude can reference
 * when creating new entries.
 *
 * Usage: pnpm generate:context
 */

import fs from "node:fs";
import path from "node:path";
import { loadSchemaContext, SLUG_PATTERN } from "./lib/schema-loader.js";
import { SCHEMA_DIR } from "./lib/utils.js";

function generateContext(): void {
  const context = loadSchemaContext();

  // Group categories by type for better readability
  const categoryGroups = groupCategories(context.categories);

  const output = `# Schema Context for Entry Creation

> **Auto-generated file** - Do not edit manually.
> Generated by \`pnpm generate:context\` from schema/*.yaml files.
> Last updated: ${new Date().toISOString()}

This file provides all valid values for creating new catalog entries.
Used by the \`/add-entry\` Claude command and validation scripts.

---

## Slug Format

Pattern: \`${SLUG_PATTERN.source}\`

**Rules:**
- Lowercase letters and numbers only
- Hyphens allowed between characters (not at start/end)
- Must be unique across all collections (manufacturers, software, hardware)
- Should match the filename (e.g., \`serum.yaml\` → \`slug: serum\`)

**Examples:**
- ✅ \`serum\`, \`massive-x\`, \`pro-tools\`, \`u87\`
- ❌ \`Serum\`, \`-serum\`, \`serum-\`, \`serum--x\`

---

## Categories

${Object.entries(categoryGroups)
  .map(
    ([group, cats]) => `### ${group}
${cats.map((c) => `- \`${c}\``).join("\n")}`
  )
  .join("\n\n")}

### Category Aliases

These aliases are accepted during validation and normalized to canonical form:

${Object.entries(context.categoryAliases)
  .map(([alias, canonical]) => `- \`${alias}\` → \`${canonical}\``)
  .join("\n")}

---

## Formats

Plugin and application formats:

${context.formats.map((f) => `- \`${f}\``).join("\n")}

**Notes:**
- \`au\` - Audio Unit (macOS/iOS)
- \`vst\` - Generic VST (when version unknown)
- \`vst2\` - Explicit VST2
- \`vst3\` - VST3
- \`aax\` - Pro Tools (current)
- \`rtas\` - Pro Tools (legacy)
- \`tdm\` - Pro Tools HD (legacy)
- \`clap\` - CLever Audio Plug-in
- \`lv2\` - Linux VST
- \`standalone\` - Standalone application

---

## Platforms

Supported operating systems:

${context.platforms.map((p) => `- \`${p}\``).join("\n")}

**Notes:**
- \`mac\` - macOS
- \`windows\` - Windows
- \`linux\` - Linux
- \`ios\` - iOS (AUv3)
- \`android\` - Android

---

## Locales

Approved locales for translations:

| Code | Name | Native Name |
|------|------|-------------|
${context.locales.map((l) => `| \`${l.code}\` | ${l.name} | ${l.nativeName} |`).join("\n")}

---

## Required Fields by Entry Type

### Manufacturer
- \`slug\` - URL-safe identifier
- \`name\` - Display name
- \`website\` - Company website URL

### Software
- \`slug\` - URL-safe identifier
- \`name\` - Display name
- \`manufacturer\` - Slug reference to manufacturer
- \`primaryCategory\` - Main category (from list above)
- \`platforms\` - Array of supported platforms
- \`identifiers\` - Bundle IDs per format (e.g., \`au: com.xferrecords.Serum\`)

### Hardware
- \`slug\` - URL-safe identifier
- \`name\` - Display name
- \`manufacturer\` - Slug reference to manufacturer
- \`primaryCategory\` - Main category (from list above)
- \`description\` - Short description (markdown)

---

## Notes

- **IDs are auto-assigned**: Never include \`id\` field manually - CI assigns nanoid on PR
- **Validate before commit**: Run \`pnpm validate\` to check entries
- **Format after edit**: Run \`pnpm format\` to ensure consistent YAML formatting
- **Check slug uniqueness**: Slugs must be unique across all collections
`;

  const outputPath = path.join(SCHEMA_DIR, "CONTEXT.md");
  fs.writeFileSync(outputPath, output, "utf-8");

  console.log(`✅ Generated ${outputPath}`);
}

/**
 * Group categories by logical type for readability
 */
function groupCategories(
  categories: string[]
): Record<string, string[]> {
  const groups: Record<string, string[]> = {
    "Software Types": [],
    "Synthesis & Instruments": [],
    "Effects": [],
    "Utility & Tools": [],
    "Hardware": [],
    "Instruments": [],
    "Genre & Style": [],
    "Other": [],
  };

  const softwareTypes = new Set([
    "daw",
    "dj-software",
    "plugin",
    "standalone",
    "suite",
  ]);

  const synthesis = new Set([
    "synthesizer",
    "virtual-instrument",
    "sampler",
    "rompler",
    "drum-machine",
    "groovebox",
    "workstation",
    "analog",
    "digital",
    "wavetable",
    "fm",
    "granular",
    "additive",
    "subtractive",
    "physical-modeling",
    "hybrid",
    "modular",
    "semi-modular",
  ]);

  const effects = new Set([
    "effect",
    "compressor",
    "limiter",
    "gate",
    "expander",
    "dynamics",
    "transient",
    "transient-shaper",
    "de-esser",
    "multiband",
    "equalizer",
    "filter",
    "exciter",
    "enhancer",
    "saturation",
    "distortion",
    "boost",
    "amp-sim",
    "cabinet-sim",
    "emulation",
    "reverb",
    "plate",
    "delay",
    "echo",
    "modulation",
    "chorus",
    "flanger",
    "phaser",
    "tremolo",
    "vibrato",
    "rotary",
    "ring-modulator",
    "pitch",
    "pitch-shifter",
    "harmonizer",
    "vocoder",
    "autotune",
    "stereo",
    "mid-side",
    "panning",
    "spatial",
    "surround",
    "binaural",
    "immersive",
  ]);

  const utility = new Set([
    "utility",
    "analyzer",
    "meter",
    "tuner",
    "noise",
    "noise-gate",
    "test-tone",
    "gain",
    "routing",
    "channel-strip",
    "preamp",
    "di-box",
    "patch-bay",
    "midi",
    "arpeggiator",
    "sequencer",
    "loop-station",
    "looper",
    "mastering",
    "loudness",
    "dither",
    "sample-rate-converter",
    "metering",
    "creative",
    "lo-fi",
    "tape",
    "vinyl",
    "glitch",
    "stutter",
    "slice",
    "grain",
    "spectral",
  ]);

  const hardware = new Set([
    "mixer",
    "audio-interface",
    "microphone",
    "studio-monitor",
    "monitor",
    "headphone",
    "headphones",
    "amplifier",
    "guitar-amplifier",
    "bass-amplifier",
    "pedal",
    "effects-pedal",
    "midi-controller",
    "control-surface",
    "turntable",
    "portable-recorder",
    "field-recorder",
    "speaker",
    "subwoofer",
    "power-amp",
    "rack-mount",
    "outboard",
    "console",
    "summing-mixer",
    "condenser",
    "dynamic",
    "ribbon",
    "shotgun",
    "lavalier",
    "usb-microphone",
    "headset",
    "cardioid",
    "modeling",
    "vocal",
  ]);

  const genre = new Set([
    "cinematic",
    "ambient",
    "electronic",
    "vintage",
    "orchestral",
    "acoustic",
    "world",
  ]);

  for (const cat of categories) {
    if (softwareTypes.has(cat)) {
      groups["Software Types"].push(cat);
    } else if (synthesis.has(cat)) {
      groups["Synthesis & Instruments"].push(cat);
    } else if (effects.has(cat)) {
      groups["Effects"].push(cat);
    } else if (utility.has(cat)) {
      groups["Utility & Tools"].push(cat);
    } else if (hardware.has(cat)) {
      groups["Hardware"].push(cat);
    } else if (genre.has(cat)) {
      groups["Genre & Style"].push(cat);
    } else {
      // Remaining are likely instruments
      groups["Instruments"].push(cat);
    }
  }

  // Remove empty groups
  for (const key of Object.keys(groups)) {
    if (groups[key].length === 0) {
      delete groups[key];
    }
  }

  return groups;
}

// Run the script
generateContext();
